### ISSUE TITLE
More descriptive errors on request failure

### ISSUE THREAD

**Issue by sbenthall** [gomicro/avenues#5]
Under a few different cases, avenues responds to an HTTP request with a 500 error and no error message.

It would be helpful if these had more specific error codes, and/or an error message that was more descriptive.

It would be especially helpful if the error message said that the error message was generated by avenues. Because avenues is working as a proxy, it's not clear when a response with 500 status is erroring in avenues or in the downstream service.

https://github.com/gomicro/avenues/blob/master/main.go#L102

https://github.com/gomicro/avenues/blob/master/main.go#L108

https://github.com/gomicro/avenues/blob/master/main.go#L116

https://github.com/gomicro/avenues/blob/master/main.go#L127

**Comment by dan9186** [comment]
Resolved through the course of #13, #14, #15, and #16
